### ISSUE TITLE
Renommage du plugin-Template

### ISSUE THREAD

**Issue by slobberbone** [NextDom/extra-tools#2]
Script de renommage du plugin-Template en plugin-XXX avec tout ce qui est en rapport avec le plugin :

- nom de la classe principale
- nom de la classe des commande
- nom des fichiers de logs
- nom de l'icone
- nom de l'ensemble des fichiers du plugin

**Comment by Sylvaner** [comment]
Ce serait bien que le plugin de base s'appelle plugin-Template et non plugin-template.
En effet ça pose problème pour le répertoire core/template. J'ai du rajouter une condition en dur juste à cause de ça.

**Comment by Sylvaner** [comment]
Qui s'occupe de ce renommage ?

**Comment by Sylvaner** [comment]
Fait
